version: '3.8'

services:
  # Frontend React App (Using alternative Dockerfile for npm auth issues)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: plottwist-frontend-local
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - /app/node_modules
    stdin_open: true
    tty: true
    networks:
      - plottwist-network

networks:
  plottwist-network:
    driver: bridge 