version: '3.8'

services:
  # Frontend React App
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plottwist-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - /app/node_modules
    stdin_open: true
    tty: true
    networks:
      - plottwist-network

networks:
  plottwist-network:
    driver: bridge 